Repository DDD-Community/DDD-9-Android3-Server, pull requests merged in 2023-11, with the labels that each got.

#24 Refactor/20 imporve duplication
  src/main/java/com/nexters/buyornot/module/post/api/dto/response/PollItemResponse.java
  src/main/java/com/nexters/buyornot/module/post/api/dto/response/PostResponse.java
  src/main/java/com/nexters/buyornot/module/post/application/PostService.java
Labels: feature, refactor

#27 Refactor/23 item update
  src/main/java/com/nexters/buyornot/module/archive/dao/ArchiveRepository.java
  src/main/java/com/nexters/buyornot/module/item/api/ItemController.java
  src/main/java/com/nexters/buyornot/module/item/application/CrawlingService.java
  src/main/java/com/nexters/buyornot/module/item/application/ItemService.java
  src/main/java/com/nexters/buyornot/module/item/dto/ably/AblyInfoDto.java
  src/main/java/com/nexters/buyornot/module/item/dto/ably/sub/Goods.java
  src/main/java/com/nexters/buyornot/module/item/dto/ably/sub/LinkedOption.java
  src/main/java/com/nexters/buyornot/module/item/dto/ably/sub/Market.java
  src/main/java/com/nexters/buyornot/module/item/dto/twentynine/TwentyNineInfoDto.java
  src/main/java/com/nexters/buyornot/module/item/dto/twentynine/sub/Data.java
  src/main/java/com/nexters/buyornot/module/item/dto/twentynine/sub/SaleInfoV2.java
  src/main/java/com/nexters/buyornot/module/item/dto/wconcept/WconceptInfoDto.java
  src/main/java/com/nexters/buyornot/module/item/dto/wconcept/sub/Category.java
  src/main/java/com/nexters/buyornot/module/item/event/ItemEventHandler.java
  src/main/java/com/nexters/buyornot/module/post/api/dto/response/PostResponse.java
  src/test/java/com/nexters/buyornot/module/archive/application/ArchiveServiceTest.java
  src/test/java/com/nexters/buyornot/module/item/application/CrawlingServiceTest.java
  src/test/java/com/nexters/buyornot/module/item/application/ItemServiceTest.java
Labels: refactor

#26 [feat] archive status
  src/main/java/com/nexters/buyornot/module/post/api/dto/response/PollItemResponse.java
  src/main/java/com/nexters/buyornot/module/post/api/dto/response/PostResponse.java
  src/main/java/com/nexters/buyornot/module/post/application/PostService.java
Labels: feature
